version: '3.8'

services:
  app:
    image: yii2-basic-app
    build: .
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - app-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii
      MYSQL_PASSWORD: yii
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  app-data:
  db-data:
