- name: Setup Yii2 App Environment
  hosts: webserver
  become: yes

  tasks:
    - name: Install required packages including nginx
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
          - git
          - php
          - php-mysql
        state: present
        update_cache: yes

    - name: Change nginx listen port to 9000
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^(\s*listen\s+)80;'
        line: '    listen 9000;'

    - name: Test nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Reload nginx service
      systemd:
        name: nginx
        state: reloaded

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Initialize Docker Swarm
      shell: docker swarm init || true
