- name: Setup Yii2 App Environment
  hosts: webserver
  become: yes

  tasks:
    - name: Install required packages including nginx
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
          - git
          - php
          - php-mysql
        state: present
        update_cache: yes

    - name: Replace nginx default site config to listen on port 9000
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 9000 default_server;
              listen [::]:9000 default_server;

              root /var/www/html;
              index index.html index.htm index.php;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;  # adjust if your PHP version differs
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify:
        - Reload nginx

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Initialize Docker Swarm
      shell: docker swarm init || true

  handlers:
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded
