name: Build & Deploy to Render via Docker Hub

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t yourdockerhubusername/yourimagename:latest .

      - name: Push Docker image
        run: |
          docker push yourdockerhubusername/yourimagename:latest

      - name: Trigger Deploy via Render API
        run: |
          curl -X POST https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{}'
