name: CI/CD Deploy Yii2 with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: sanjeevashwin/yii2-app:latest

      - name: Save SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook to Set Up EC2
        run: |
         export ANSIBLE_HOST_KEY_CHECKING=False
         ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml --private-key ~/.ssh/id_rsa -u ubuntu
      
      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            sudo docker pull sanjeevashwin/yii2-app:latest
            
            echo "Deploying using docker-compose..."
            cd /home/ubuntu
            sudo docker stack deploy -c docker-compose.yaml yii2_stack
            
            echo "Creating Nginx config for reverse proxy on port 9000..."
            sudo bash -c 'cat > /etc/nginx/sites-available/52.66.132.71.conf <<EOF
            server {
                listen 9000;
                server_name 52.66.132.71;

                location / {
                    proxy_pass http://localhost:8080;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                }
            }
            EOF'

            echo "Enabling Nginx site and restarting nginx..."
            sudo ln -sf /etc/nginx/sites-available/52.66.132.71.conf /etc/nginx/sites-enabled/52.66.132.71.conf 
            sudo nginx -t && sudo systemctl restart nginx
