name: Deploy to Render

on:
  push:
    branches: [dev]   # or your production branch

jobs:
  deploy:
    name: Build and Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Render Docker registry (optional)
        run: echo "${{ secrets.RENDER_API_KEY }}" | docker login registry.render.com -u _json_key --password-stdin

      - name: Build Docker image
        run: |
          docker build -t registry.render.com/your-service-name:latest .

      - name: Push Docker image
        run: |
          docker push registry.render.com/your-service-name:latest

      - name: Trigger Deploy via Render API
        run: |
          curl -X POST https://api.render.com/v1/services/SERVICE_ID/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{}'
