name: Deploy to Render

on:
  push:
    branches: [dev]  # Change to your branch if needed (main or dev)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy via Render API
        run: |
          curl -X POST https://api.render.com/v1/services/srv-d194dj3uibrs73bqaqn0/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{}'
